# Generated by Django 4.1 on 2022-08-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
